//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod access_tokens;
pub mod attempt_logins;
pub mod banned_logins;
pub mod failed_logins;
pub mod permissions;
pub mod role_permissions;
pub mod roles;
pub mod system_configs;
pub mod user_roles;
pub mod users;
