//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::access_tokens::Entity as AccessTokens;
pub use super::attempt_logins::Entity as AttemptLogins;
pub use super::banned_logins::Entity as BannedLogins;
pub use super::failed_logins::Entity as FailedLogins;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::system_configs::Entity as SystemConfigs;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
